### ISSUE TITLE
Needs README content

### ISSUE THREAD

**Issue by nexdrew** [brad-bowie/shoehorn#1]
I was trolling npm and noticed you published this package without any documentation.

Because of this, I was unable to use your package within the timeframe I was given by my boss, and I was fired.

Please be mindful of the large Node community and restrain from publishing to npm until complete documentation is available. I'd like to avoid further unnecessary firings, if at all possible!

**Comment by nexdrew** [comment]
~~I'm~~ _Edit: edited_

**Comment by nexdrew** [comment]
~~reporting~~ _Edit: edited_

**Comment by nexdrew** [comment]
~~this~~ _Edit: edited_

**Comment by nexdrew** [comment]
~~as~~ _Edit: edited_

**Comment by nexdrew** [comment]
~~abusive~~ _Edit: edited_

**Comment by nexdrew** [comment]
~~behavior.~~ _Edit: edited_

**Comment by booee** [comment]
Fixed.
